[template]
src = "keepalived.conf.tmpl"
dest = "/etc/keepalived/keepalived.conf"
keys = [
    "/keepalived/vrrp/state",
    "/keepalived/vrrp/priority",
    "/keepalived/unicast/src/ip",
    "/keepalived/unicast/peer",
    "/keepalived/auth/pass",
    "/keepalived/check/ip",
    "/keepalived/check/port"
]
